version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    command: yarn dev ## comando a executar
    ports:
      - "3333:3333" ## redirecionamento de porta quando chegar alguma requisição na porta 3333 chama o container na porta 3333
    volumes:
      - .:/usr/app_node ## monitora a pasta atual . e envia as alterações para /usr/app_node

